### ISSUE TITLE
Security Check. bad AS_ID

### ISSUE THREAD

**Issue by T365** [kpn-iot/lora-reference#3]
xxxxxx/example.php:27:string 'Security Check. bad AS_ID' (length=25)

**Comment by maerduq** [comment]
Hi T365,

Your issue has gone unnoticed for quite some time (understatement), my apologies for that.

Another user has found that the LRC AS Key needs to be cast to lowercase before the token is calculated. We have updated the example code to account for that. Hopefully it will fix the issue for you as well.
