### ISSUE TITLE
lrcAsKey and capitalized characters.

### ISSUE THREAD

**Issue by rikwilbrink** [kpn-iot/lora-reference#4]
I've been struggling quite some time, and it seems that ThingPark saves the application server lrcAsKey with lowercase, or the api compares the stored value in lowercase.

Steps to reproduce:
in https://www.kpn-lora.com/deviceManager/ create a new Application Server.
Safe the LrcAsKey with a valid key with uppercase characters and digits.

run the https://github.com/kpn-iot/lora-reference/blob/master/downlink-request/nodejs/example.js
with the same uppercase characters. 
API will complain about "Security Check. bad token"

After a day of trying to get this to work, i've simply tried lowercase the lrcAsKey, even though i was sure i've safed it in uppercase in ThingPark. And Yes, it works:
I received the message: "Request queued by LRC"

So to fix it, make sure you use the LrcAsKey in lowercase (digits remain the same)

`    
const lrcAsKey = "FEA63EC1582A03194F1705B16EABC325";
const hashIn = queryString + **lrcAsKey.toLowerCase();**
const tokenInt = sjcl.hash.sha256.hash(hashIn);
const token = sjcl.codec.hex.fromBits(tokenInt);
`

@kpn-iot please revise the reference script and provide a sensible documentation about it. The solution shouldn't require such a trial and error solution.

**Comment by maerduq** [comment]
Hi rikwilbrink,

Sorry to see the example code did not cover this tedious issue, my apologies for your lost time. We had accounted for this detail in the token verification PHP example code, but we forgot to add it to the downlink examples. 

We adopted your fix and fixed the PHP example as well. We will make sure this will be highlighted in the technical service description as well.

Regards,
Paul
